### ISSUE TITLE
Grok won't build on CentOS

### ISSUE THREAD

**Issue by seth-shaw-unlv** [Islandora-Devops/ansible-role-grok#1]
Need to use Yum for RH/Cent instead of apt. Also, cmake is cmake3 on RH/CentOS, so the build instructions need to be customized.

**Comment by jonathangreen** [comment]
Merged with https://github.com/Islandora-Devops/ansible-role-grok/commit/b98c3d3916829b4f60dccabeb4f69eb9e4e2d63f
